version: '3.9'

services:
  angular-app:
    build:
      context: . # Aquí iría la ruta de la carpeta donde está el Dockerfile
      dockerfile: Dockerfile # Aquí iría el nombre del Dockerfile
    working_dir: /usr/local/app # Directorio de trabajo dentro del contenedor
    ports:
      - "80:80"