version: '3.9'

services:
  angular-app:
    build:
      context: . # Aquí iría la ruta de la carpeta donde está el Dockerfile
      dockerfile: Dockerfile # Aquí iría el nombre del Dockerfile
    working_dir: /app # Directorio de trabajo dentro del contenedor
    # command: sleep infinity
    ports:
      - "4200:4200"
    command:
      sh -c "ng serve --host 0.0.0.0 --disable-host-check"