# Utiliza la imagen oficial de MariaDB como base
FROM mariadb:jammy

# Variables de entorno
ENV MARIADB_USER=mariadb_user
ENV MARIADB_PASSWORD=mariadb_user
ENV MARIADB_ROOT_PASSWORD=root-mariadb-user
ENV MARIADB_DATABASE=world-db

# Exponer el puerto
EXPOSE 3306
