version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
      - 5001:5001
    working_dir: /app
    command: sleep infinity
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000;http://+:5001;
      - ASPNETCORE_HTTP_PORT=http://+:5001;http://+:5000